export const COMMON_WORDS = [
  "apple", "house", "water", "table", "chair",
  "book", "phone", "light", "music", "bread",
  "clock", "plant", "glass", "paper", "stone"
];


export const COUNTRY_MAP = {
  AFG: { language: "fa",  name: "Afghanistan" },
  ALB: { language: "sq",  name: "Albania" },
  DZA: { language: "ar",  name: "Algeria" },
  AND: { language: "ca",  name: "Andorra" },
  AGO: { language: "pt",  name: "Angola" },
  ARG: { language: "es",  name: "Argentina" },
  ARM: { language: "hy",  name: "Armenia" },
  AUS: { language: "en",  name: "Australia" },
  AUT: { language: "de",  name: "Austria" },
  AZE: { language: "az",  name: "Azerbaijan" },
  BHS: { language: "en",  name: "Bahamas" },
  BHR: { language: "ar",  name: "Bahrain" },
  BGD: { language: "bn",  name: "Bangladesh" },
  BLR: { language: "be",  name: "Belarus" },
  BEL: { language: "nl",  name: "Belgium" },
  BLZ: { language: "en",  name: "Belize" },
  BEN: { language: "fr",  name: "Benin" },
  BTN: { language: "dz",  name: "Bhutan" },
  BOL: { language: "es",  name: "Bolivia" },
  BIH: { language: "bs",  name: "Bosnia and Herzegovina" },
  BWA: { language: "en",  name: "Botswana" },
  BRA: { language: "pt",  name: "Brazil" },
  BRN: { language: "ms",  name: "Brunei" },
  BGR: { language: "bg",  name: "Bulgaria" },
  BFA: { language: "fr",  name: "Burkina Faso" },
  BDI: { language: "fr",  name: "Burundi" },
  CPV: { language: "pt",  name: "Cape Verde" },
  KHM: { language: "km",  name: "Cambodia" },
  CMR: { language: "fr",  name: "Cameroon" },
  CAN: { language: "en",  name: "Canada" },
  CAF: { language: "fr",  name: "Central African Republic" },
  TCD: { language: "fr",  name: "Chad" },
  CHL: { language: "es",  name: "Chile" },
  CHN: { language: "zh",  name: "China" },
  COL: { language: "es",  name: "Colombia" },
  COM: { language: "ar",  name: "Comoros" },
  COD: { language: "fr",  name: "DR Congo" },
  COG: { language: "fr",  name: "Republic of the Congo" },
  CRI: { language: "es",  name: "Costa Rica" },
  HRV: { language: "hr",  name: "Croatia" },
  CUB: { language: "es",  name: "Cuba" },
  CYP: { language: "el",  name: "Cyprus" },
  CZE: { language: "cs",  name: "Czech Republic" },
  DNK: { language: "da",  name: "Denmark" },
  DJI: { language: "ar",  name: "Djibouti" },
  DOM: { language: "es",  name: "Dominican Republic" },
  ECU: { language: "es",  name: "Ecuador" },
  EGY: { language: "ar",  name: "Egypt" },
  SLV: { language: "es",  name: "El Salvador" },
  GNQ: { language: "es",  name: "Equatorial Guinea" },
  ERI: { language: "ti",  name: "Eritrea" },
  EST: { language: "et",  name: "Estonia" },
  SWZ: { language: "en",  name: "Eswatini" },
  ETH: { language: "am",  name: "Ethiopia" },
  FJI: { language: "en",  name: "Fiji" },
  FIN: { language: "fi",  name: "Finland" },
  FRA: { language: "fr",  name: "France" },
  GAB: { language: "fr",  name: "Gabon" },
  GMB: { language: "en",  name: "Gambia" },
  GEO: { language: "ka",  name: "Georgia" },
  DEU: { language: "de",  name: "Germany" },
  GHA: { language: "en",  name: "Ghana" },
  GRC: { language: "el",  name: "Greece" },
  GTM: { language: "es",  name: "Guatemala" },
  GIN: { language: "fr",  name: "Guinea" },
  GNB: { language: "pt",  name: "Guinea-Bissau" },
  GUY: { language: "en",  name: "Guyana" },
  HTI: { language: "ht",  name: "Haiti" },
  HND: { language: "es",  name: "Honduras" },
  HUN: { language: "hu",  name: "Hungary" },
  ISL: { language: "is",  name: "Iceland" },
  IND: { language: "hi",  name: "India" },
  IDN: { language: "ind", name: "Indonesia" },
  IRN: { language: "fa",  name: "Iran" },
  IRQ: { language: "ar",  name: "Iraq" },
  IRL: { language: "en",  name: "Ireland" },
  ISR: { language: "he",  name: "Israel" },
  ITA: { language: "it",  name: "Italy" },
  JAM: { language: "en",  name: "Jamaica" },
  JPN: { language: "ja",  name: "Japan" },
  JOR: { language: "ar",  name: "Jordan" },
  KAZ: { language: "kk",  name: "Kazakhstan" },
  KEN: { language: "sw",  name: "Kenya" },
  PRK: { language: "ko",  name: "North Korea" },
  KOR: { language: "ko",  name: "South Korea" },
  KWT: { language: "ar",  name: "Kuwait" },
  KGZ: { language: "ky",  name: "Kyrgyzstan" },
  LAO: { language: "lo",  name: "Laos" },
  LVA: { language: "lv",  name: "Latvia" },
  LBN: { language: "ar",  name: "Lebanon" },
  LSO: { language: "st",  name: "Lesotho" },
  LBR: { language: "en",  name: "Liberia" },
  LBY: { language: "ar",  name: "Libya" },
  LIE: { language: "de",  name: "Liechtenstein" },
  LTU: { language: "lt",  name: "Lithuania" },
  LUX: { language: "lb",  name: "Luxembourg" },
  MDG: { language: "mg",  name: "Madagascar" },
  MWI: { language: "en",  name: "Malawi" },
  MYS: { language: "ms",  name: "Malaysia" },
  MDV: { language: "dv",  name: "Maldives" },
  MLI: { language: "fr",  name: "Mali" },
  MLT: { language: "mt",  name: "Malta" },
  MRT: { language: "ar",  name: "Mauritania" },
  MUS: { language: "en",  name: "Mauritius" },
  MEX: { language: "es",  name: "Mexico" },
  MDA: { language: "ro",  name: "Moldova" },
  MCO: { language: "fr",  name: "Monaco" },
  MNG: { language: "mn",  name: "Mongolia" },
  MNE: { language: "sr",  name: "Montenegro" },
  MAR: { language: "ar",  name: "Morocco" },
  MOZ: { language: "pt",  name: "Mozambique" },
  MMR: { language: "my",  name: "Myanmar" },
  NAM: { language: "en",  name: "Namibia" },
  NPL: { language: "ne",  name: "Nepal" },
  NLD: { language: "nl",  name: "Netherlands" },
  NZL: { language: "en",  name: "New Zealand" },
  NIC: { language: "es",  name: "Nicaragua" },
  NER: { language: "fr",  name: "Niger" },
  NGA: { language: "en",  name: "Nigeria" },
  MKD: { language: "mk",  name: "North Macedonia" },
  NOR: { language: "no",  name: "Norway" },
  OMN: { language: "ar",  name: "Oman" },
  PAK: { language: "ur",  name: "Pakistan" },
  PAN: { language: "es",  name: "Panama" },
  PNG: { language: "en",  name: "Papua New Guinea" },
  PRY: { language: "es",  name: "Paraguay" },
  PER: { language: "es",  name: "Peru" },
  PHL: { language: "tl",  name: "Philippines" },
  POL: { language: "pl",  name: "Poland" },
  PRT: { language: "pt",  name: "Portugal" },
  QAT: { language: "ar",  name: "Qatar" },
  ROU: { language: "ro",  name: "Romania" },
  RUS: { language: "ru",  name: "Russia" },
  RWA: { language: "rw",  name: "Rwanda" },
  SAU: { language: "ar",  name: "Saudi Arabia" },
  SEN: { language: "fr",  name: "Senegal" },
  SRB: { language: "sr",  name: "Serbia" },
  SLE: { language: "en",  name: "Sierra Leone" },
  SGP: { language: "en",  name: "Singapore" },
  SVK: { language: "sk",  name: "Slovakia" },
  SVN: { language: "sl",  name: "Slovenia" },
  SOM: { language: "so",  name: "Somalia" },
  ZAF: { language: "af",  name: "South Africa" },
  SSD: { language: "en",  name: "South Sudan" },
  ESP: { language: "es",  name: "Spain" },
  LKA: { language: "si",  name: "Sri Lanka" },
  SDN: { language: "ar",  name: "Sudan" },
  SUR: { language: "nl",  name: "Suriname" },
  SWE: { language: "sv",  name: "Sweden" },
  CHE: { language: "de",  name: "Switzerland" },
  SYR: { language: "ar",  name: "Syria" },
  TWN: { language: "zh",  name: "Taiwan" },
  TJK: { language: "tg",  name: "Tajikistan" },
  TZA: { language: "sw",  name: "Tanzania" },
  THA: { language: "th",  name: "Thailand" },
  TLS: { language: "pt",  name: "Timor-Leste" },
  TGO: { language: "fr",  name: "Togo" },
  TTO: { language: "en",  name: "Trinidad and Tobago" },
  TUN: { language: "ar",  name: "Tunisia" },
  TUR: { language: "tr",  name: "Turkey" },
  TKM: { language: "tk",  name: "Turkmenistan" },
  UGA: { language: "en",  name: "Uganda" },
  UKR: { language: "uk",  name: "Ukraine" },
  ARE: { language: "ar",  name: "United Arab Emirates" },
  GBR: { language: "en",  name: "United Kingdom" },
  USA: { language: "en",  name: "United States" },
  URY: { language: "es",  name: "Uruguay" },
  UZB: { language: "uz",  name: "Uzbekistan" },
  VEN: { language: "es",  name: "Venezuela" },
  VNM: { language: "vi",  name: "Vietnam" },
  YEM: { language: "ar",  name: "Yemen" },
  ZMB: { language: "en",  name: "Zambia" },
  ZWE: { language: "en",  name: "Zimbabwe" },
};